services:
  pop:
    restart: always
    #image: rabbitmq:latest
    image: rabbitmq:management
    env_file: .env
    volumes:
      - poptape_rabbitdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    networks:
      - poptape
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
networks:
  poptape:
    external: true
volumes:
  poptape_rabbitdata:
